language: node_js
node_js:
  - '8'
  - '10'
  - '12'
before_install: 'sudo add-apt-repository -y ppa:inkscape.dev/stable && sudo apt-get update && sudo apt-get install -y inkscape && inkscape --version'
script: 'npm run-script travis'
